export const mapPropertyListFromViewModelToApi = property => {
    return {
        title: property.title,
        notes: property.notes,
        email: property.email,
        phone: property.phone,
        price: parseFloat(property.price),
        saleTypesIds: property.saleTypes,
        address: property.address,
        city: property.city,
        provinceId: property.province,
        squareMeter: parseFloat(property.squareMeter),
        rooms: property.rooms,
        bathrooms: parseInt(property.bathrooms),
        locationUrl: property.locationUrl,
        mainFeatures: property.mainFeatures,
        equipmentsIds: property.equipments,
        images: property.images,
    };
};

    // title: '',
    // notes: '',
    // email: '',
    // phone: '',
    // price: '',
    // saleTypes: [],
    // address: '',
    // city: '',
    // province: '',
    // squareMeter: '',
    // rooms: '',
    // bathrooms: '',
    // locationUrl: '',
    // mainFeatures: '',
    // equipments: '', 
    // images: '',
