export const mapPropertyListFromViewModelToApi = newProperty => {
    return {
        title: newProperty.title,
        notes: newProperty.notes,
        email: newProperty.email,
        phone: newProperty.phone,
        price: parseFloat(newProperty.price),
        saleTypes: newProperty.saleTypes,
        address: newProperty.address,
        city: newProperty.city,
        province: newProperty.province,
        squareMeter: parseFloat(newProperty.squareMeter),
        rooms: newProperty.rooms,
        bathrooms: parseInt(newProperty.bathrooms),
        locationUrl: newProperty.locationUrl,
        mainFeatures: newProperty.mainFeatures,
        equipments: newProperty.equipments,
        images: newProperty.images,
    };
};

    // title: '',
    // notes: '',
    // email: '',
    // phone: '',
    // price: '',
    // saleTypes: [],
    // address: '',
    // city: '',
    // province: '',
    // squareMeter: '',
    // rooms: '',
    // bathrooms: '',
    // locationUrl: '',
    // mainFeatures: '',
    // equipments: '', 
    // images: '',
